src/web/controllers/bookmark.py
import logging
import itertools
from datetime import datetime, timedelta

from bootstrap import db
from web.models import Bookmark
from .abstract import AbstractController
from .tag import BookmarkTagController

logger = logging.getLogger(__name__)


class BookmarkController(AbstractController):
    _db_cls = Bookmark

    def count_by_href(self, **filters):
        return self._count_by(Bookmark.href, filters)

    def update(self, filters, attrs):
        BookmarkTagController(self.user_id) \
                                .read(**{'bookmark_id': filters["id"]}) \
                                .delete()

        for tag in attrs['tags']:
            BookmarkTagController(self.user_id).create(
                                            **{'text': tag.text,
                                                'id': tag.id,
                                                'bookmark_id': tag.bookmark_id,
                                                'user_id': tag.user_id})

        del attrs['tags']
        return super().update(filters, attrs)

src/web/views/article.py
from datetime import datetime, timedelta
from flask import (Blueprint, g, render_template, redirect,
                   flash, url_for, make_response, request)

from flask_babel import gettext
from flask_login import login_required, current_user


from bootstrap import db
from lib.utils import clear_string, redirect_url
from lib.data import export_json
from web.controllers import (ArticleController, UserController,
                            CategoryController)
from web.lib.view_utils import etag_match

articles_bp = Blueprint('articles', __name__, url_prefix='/articles')
article_bp = Blueprint('article', __name__, url_prefix='/article')


@article_bp.route('/redirect/<int:article_id>', methods=['GET'])
@login_required
def redirect_to_article(article_id):
    contr = ArticleController(current_user.id)
    article = contr.get(id=article_id)
    if not article.readed:
        contr.update({'id': article.id}, {'readed': True})
    return redirect(article.link)


@article_bp.route('/<int:article_id>', methods=['GET'])
@login_required
@etag_match
def article(article_id=None):
    """
    Presents an article.
    """
    article = ArticleController(current_user.id).get(id=article_id)
    return render_template('article.html',
                           head_titles=[clear_string(article.title)],
                           article=article)

@article_bp.route('/public/<int:article_id>', methods=['GET'])
@etag_match
def article_pub(article_id=None):
    """
    Presents an article of a public feed if the profile of the owner is also
    public.
    """
    article = ArticleController().get(id=article_id)
    if article.source.private or not article.source.user.is_public_profile:
        return render_template('errors/404.html'), 404
    return render_template('article_pub.html',
                           head_titles=[clear_string(article.title)],
                           article=article)


@article_bp.route('/like/<int:article_id>', methods=['GET'])
@login_required
def like(article_id=None):
    """
    Mark or unmark an article as favorites.
    """
    art_contr = ArticleController(current_user.id)
    article = art_contr.get(id=article_id)
    art_contr = art_contr.update({'id': article_id},
                                 {'like': not article.like})
    return redirect(redirect_url())


@article_bp.route('/delete/<int:article_id>', methods=['GET'])
@login_required
def delete(article_id=None):
    """
    Delete an article from the database.
    """
    article = ArticleController(current_user.id).delete(article_id)
    flash(gettext('Article %(article_title)s deleted',
                  article_title=article.title), 'success')
    return redirect(url_for('home'))


@articles_bp.route('/history', methods=['GET'])
@articles_bp.route('/history/<int:year>', methods=['GET'])
@articles_bp.route('/history/<int:year>/<int:month>', methods=['GET'])
@login_required
def history(year=None, month=None):
    cntr, artcles = ArticleController(current_user.id).get_history(year, month)
    return render_template('history.html', articles_counter=cntr,
                           articles=artcles, year=year, month=month)


@article_bp.route('/mark_as/<string:new_value>', methods=['GET'])
@article_bp.route('/mark_as/<string:new_value>/article/<int:article_id>',
                  methods=['GET'])
@login_required
def mark_as(new_value='read', feed_id=None, article_id=None):
    """
    Mark all unreaded articles as read.
    """
    readed = new_value == 'read'
    art_contr = ArticleController(current_user.id)
    filters = {'readed': not readed}
    if feed_id is not None:
        filters['feed_id'] = feed_id
        message = 'Feed marked as %s.'
    elif article_id is not None:
        filters['id'] = article_id
        message = 'Article marked as %s.'
    else:
        message = 'All article marked as %s.'
    art_contr.update(filters, {"readed": readed})
    flash(gettext(message % new_value), 'info')

    if readed:
        return redirect(redirect_url())
    return redirect('home')


@articles_bp.route('/expire_articles', methods=['GET'])
@login_required
def expire():
    """
    Delete articles older than the given number of weeks.
    """
    current_time = datetime.utcnow()
    weeks_ago = current_time - timedelta(int(request.args.get('weeks', 10)))
    art_contr = ArticleController(current_user.id)

    query = art_contr.read(__or__={'date__lt': weeks_ago,
                                   'retrieved_date__lt': weeks_ago})
    count = query.count()
    query.delete()
    db.session.commit()
    flash(gettext('%(count)d articles deleted', count=count), 'info')
    return redirect(redirect_url())


@articles_bp.route('/export', methods=['GET'])
@login_required
def export():
    """
    Export to OPML or JSON.
    """
    user = UserController(current_user.id).get(id=current_user.id)
    if request.args.get('format') == "JSON":
        # Export to JSON for the export of account.
        try:
            json_result = export_json(user)
        except Exception as e:
            flash(gettext("Error when exporting articles."), 'danger')
            return redirect(redirect_url())
        response = make_response(json_result)
        response.mimetype = 'application/json'
        response.headers["Content-Disposition"] \
                = 'attachment; filename=account.json'
    elif request.args.get('format') == "OPML":
        # Export to the OPML format.
        categories = {cat.id: cat.dump()
                for cat in CategoryController(user.id).read()}
        response = make_response(render_template('opml.xml', user=user,
                                                categories=categories,
                                                now=datetime.now()))
        response.headers['Content-Type'] = 'application/xml'
        response.headers['Content-Disposition'] = 'attachment; filename=feeds.opml'
    else:
        flash(gettext('Export format not supported.'), 'warning')
        return redirect(redirect_url())
    return response

src/web/views/bookmark.py
#! /usr/bin/env python
#-*- coding: utf-8 -*-

# Newspipe - A Web based news aggregator.
# Copyright (C) 2010-2017  Cédric Bonhomme - https://www.cedricbonhomme.org
#
# For more information : https://gitlab.com/newspipe/newspipe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

__author__ = "Cedric Bonhomme"
__version__ = "$Revision: 0.1 $"
__date__ = "$Date: 2017/05/24 $"
__revision__ = "$Date: 2017/05/24 $"
__copyright__ = "Copyright (c) Cedric Bonhomme"
__license__ = "AGPLv3"

import logging
import datetime
from werkzeug.exceptions import BadRequest

from flask import Blueprint, render_template, flash, \
                  redirect, request, url_for, make_response
from flask_babel import gettext
from flask_login import login_required, current_user
from flask_paginate import Pagination, get_page_args
from sqlalchemy import desc

import conf
from lib.utils import redirect_url
from lib.data import import_pinboard_json, export_bookmarks
from bootstrap import db
from web.forms import BookmarkForm
from web.controllers import BookmarkController, BookmarkTagController
from web.models import BookmarkTag

logger = logging.getLogger(__name__)
bookmarks_bp = Blueprint('bookmarks', __name__, url_prefix='/bookmarks')
bookmark_bp = Blueprint('bookmark', __name__, url_prefix='/bookmark')


@bookmarks_bp.route('/', defaults={'per_page': '50'}, methods=['GET'])
@bookmarks_bp.route('/<string:status>', defaults={'per_page': '50'},
                                                                methods=['GET'])
def list_(per_page, status='all'):
    "Lists the bookmarks."
    head_titles = [gettext("Bookmarks")]
    user_id = None
    filters = {}
    tag = request.args.get('tag', None)
    if tag:
        filters['tags_proxy__contains'] = tag
    query = request.args.get('query', None)
    if query:
        query_regex = '%' + query + '%'
        filters['__or__'] = {'title__ilike': query_regex,
                            'description__ilike': query_regex}
    if current_user.is_authenticated:
        # query for the bookmarks of the authenticated user
        user_id = current_user.id
        if status == 'public':
            # load public bookmarks only
            filters['shared'] = True
        elif status == 'private':
            # load private bookmarks only
            filters['shared'] = False
        else:
            # no filter: load shared and public bookmarks
            pass
        if status == 'unread':
            filters['to_read'] = True
        else:
            pass
    else:
        # query for the shared bookmarks (of all users)
        head_titles = [gettext("Recent bookmarks")]
        not_created_before = datetime.datetime.today() - \
                                                    datetime.timedelta(days=900)
        filters['time__gt'] = not_created_before # only "recent" bookmarks
        filters['shared'] = True

    bookmarks = BookmarkController(user_id) \
                    .read(**filters) \
                    .order_by(desc('time'))

    #tag_contr = BookmarkTagController(user_id)
    #tag_contr.read().join(bookmarks).all()

    page, per_page, offset = get_page_args()
    pagination = Pagination(page=page, total=bookmarks.count(),
                            css_framework='bootstrap3',
                            search=False, record_name='bookmarks',
                            per_page=per_page)

    return render_template('bookmarks.html',
                            head_titles=head_titles,
                            bookmarks=bookmarks.offset(offset).limit(per_page),
                            pagination=pagination,
                            tag=tag,
                            query=query)


@bookmark_bp.route('/create', methods=['GET'])
@bookmark_bp.route('/edit/<int:bookmark_id>', methods=['GET'])
@login_required
def form(bookmark_id=None):
    "Form to create/edit bookmarks."
    action = gettext("Add a new bookmark")
    head_titles = [action]
    if bookmark_id is None:
        return render_template('edit_bookmark.html', action=action,
                               head_titles=head_titles, form=BookmarkForm())
    bookmark = BookmarkController(current_user.id).get(id=bookmark_id)
    action = gettext('Edit bookmark')
    head_titles = [action]
    form = BookmarkForm(obj=bookmark)
    form.tags.data = ", ".join(bookmark.tags_proxy)
    return render_template('edit_bookmark.html', action=action,
                           head_titles=head_titles, bookmark=bookmark,
                           form=form)


@bookmark_bp.route('/create', methods=['POST'])
@bookmark_bp.route('/edit/<int:bookmark_id>', methods=['POST'])
@login_required
def process_form(bookmark_id=None):
    "Process the creation/edition of bookmarks."
    form = BookmarkForm()
    bookmark_contr = BookmarkController(current_user.id)
    tag_contr = BookmarkTagController(current_user.id)

    if not form.validate():
        return render_template('edit_bookmark.html', form=form)

    if form.title.data == '':
        title = form.href.data
    else:
        title = form.title.data

    bookmark_attr = {'href': form.href.data,
                    'description': form.description.data,
                    'title': title,
                    'shared': form.shared.data,
                    'to_read': form.to_read.data}

    if bookmark_id is not None:
        tags = []
        for tag in form.tags.data.split(','):
            new_tag = tag_contr.create(text=tag.strip(), user_id=current_user.id,
                                        bookmark_id=bookmark_id)
            tags.append(new_tag)
        bookmark_attr['tags'] = tags
        bookmark_contr.update({'id': bookmark_id}, bookmark_attr)
        flash(gettext('Bookmark successfully updated.'), 'success')
        return redirect(url_for('bookmark.form', bookmark_id=bookmark_id))

    # Create a new bookmark
    new_bookmark = bookmark_contr.create(**bookmark_attr)
    tags = []
    for tag in form.tags.data.split(','):
        new_tag = tag_contr.create(text=tag.strip(), user_id=current_user.id,
                                    bookmark_id=new_bookmark.id)
        tags.append(new_tag)
    bookmark_attr['tags'] = tags
    bookmark_contr.update({'id': new_bookmark.id}, bookmark_attr)
    flash(gettext('Bookmark successfully created.'), 'success')
    return redirect(url_for('bookmark.form', bookmark_id=new_bookmark.id))


@bookmark_bp.route('/delete/<int:bookmark_id>', methods=['GET'])
@login_required
def delete(bookmark_id=None):
    "Delete a bookmark."
    bookmark = BookmarkController(current_user.id).delete(bookmark_id)
    flash(gettext("Bookmark %(bookmark_name)s successfully deleted.",
                  bookmark_name=bookmark.title), 'success')
    return redirect(url_for('bookmarks.list_'))


@bookmarks_bp.route('/delete', methods=['GET'])
@login_required
def delete_all():
    "Delete all bookmarks."
    bookmark = BookmarkController(current_user.id).read().delete()
    db.session.commit()
    flash(gettext("Bookmarks successfully deleted."), 'success')
    return redirect(redirect_url())


@bookmark_bp.route('/bookmarklet', methods=['GET', 'POST'])
@login_required
def bookmarklet():
    bookmark_contr = BookmarkController(current_user.id)
    href = (request.args if request.method == 'GET' else request.form)\
            .get('href', None)
    if not href:
        flash(gettext("Couldn't add bookmark: url missing."), "error")
        raise BadRequest("url is missing")
    title = (request.args if request.method == 'GET' else request.form)\
            .get('title', None)
    if not title:
        title = href

    bookmark_exists = bookmark_contr.read(**{'href': href}).all()
    if bookmark_exists:
        flash(gettext("Couldn't add bookmark: bookmark already exists."),
                "warning")
        return redirect(url_for('bookmark.form',
                                            bookmark_id=bookmark_exists[0].id))

    bookmark_attr = {'href': href,
                    'description': '',
                    'title': title,
                    'shared': True,
                    'to_read': True}

    new_bookmark = bookmark_contr.create(**bookmark_attr)
    flash(gettext('Bookmark successfully created.'), 'success')
    return redirect(url_for('bookmark.form', bookmark_id=new_bookmark.id))


@bookmark_bp.route('/import_pinboard', methods=['POST'])
@login_required
def import_pinboard():
    bookmarks = request.files.get('jsonfile', None)
    if bookmarks:
        try:
            nb_bookmarks = import_pinboard_json(current_user, bookmarks.read())
            flash(gettext("%(nb_bookmarks)s bookmarks successfully imported.",
                          nb_bookmarks=nb_bookmarks), 'success')
        except Exception as e:
            flash(gettext('Error when importing bookmarks.'), 'error')

    return redirect(redirect_url())


@bookmarks_bp.route('/export', methods=['GET'])
@login_required
def export():
    bookmarks = export_bookmarks(current_user)
    response = make_response(bookmarks)
    response.mimetype = 'application/json'
    response.headers["Content-Disposition"] \
            = 'attachment; filename=newspipe_bookmarks_export.json'
    return response

src/web/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="well">
        <h1>{{ _('About') }}</h1>
        <p>
        {{ _('Newspipe is a news aggregator platform.') }}
        {{ _('You can easily <a href="https://newspipe.readthedocs.io/en/latest/deployment.html">install Newspipe on your server</a>.') }}
        {{ _('Alternatively, you can deploy your own copy using this button:') }}</p>
        <a class="reference external image-reference" href="https://heroku.com/deploy?template=https://gitlab.com/newspipe/newspipe.git"><img alt="https://www.herokucdn.com/deploy/button.png" src="https://www.herokucdn.com/deploy/button.png" /></a></p>
        <p>{{ _('This software is under AGPLv3 license. You are welcome to copy, modify or
        redistribute the <a href="https://gitlab.com/newspipe/newspipe">source code</a>
        according to the <a href="https://www.gnu.org/licenses/agpl-3.0.html">Affero GPL</a> license.') }}</p>
        <p>{{ _('Found a bug? Report it <a href="https://gitlab.com/newspipe/newspipe/issues">here</a>.') }}</p>
        <p><a href="{{ url_for('about_more') }}">{{ _('More information') }}</a> {{ _('about this instance.') }}</p>
    </div>
    <div class="well">
        <h1>{{ _('Help') }}</h1>
        <p>{{ _('The documentation of the API is <a href="https://newspipe.readthedocs.io/en/latest/web-services-v3.html">here</a>.') }}</p>
        <p>{{ _('Contact')}}: <a href="mailto:{{ contact }}">{{ contact }}</a></p>
        <p>{{ _('You can subscribe to new feeds with a bookmarklet. Drag the following button to your browser bookmarks.') }}</p>
        {{ _('<a class="btn btn-default" href="%(bookmarklet)s" rel="bookmark">Subscribe to this feed using Newspipe</a>', bookmarklet='javascript:window.location="%s?url="+encodeURIComponent(document.location)' % url_for('feed.bookmarklet', _external=True)) }}
    </div>
</div><!-- /.container -->
{% endblock %}

src/web/templates/article.html
{% extends "layout.html" %}
{% block content %}
<div class="container" data-article="{{ article.id }}">
    <div class="well">
        <h2><a href="{{ article.link  }}" target="_blank">{{ article.title|safe }}</a></h2>
        <h3>{{ _('from') }} <a href="/feed/{{ article.source.id }}">{{ article.source.title }}</a></h3>
        <a href="{{ url_for("article.delete", article_id=article.id) }}"><i class="glyphicon glyphicon-remove" title="{{ _('Delete this article') }}"></i></a>
        {% if article.like %}
            <a href="#"><i class="glyphicon glyphicon-star like" title="{{ _('One of your favorites') }}"></i></a>
        {% else %}
            <a href="#"><i class="glyphicon glyphicon-star-empty like" title="{{ _('Click if you like this article') }}"></i></a>
        {% endif %}
        {% if article.readed %}
            <a href="#"><i class="glyphicon glyphicon-unchecked readed" title="{{ _('Mark this article as unread') }}"></i></a>
        {% else %}
            <a href="#"><i class="glyphicon glyphicon-check readed" title="{{ _('Mark this article as read') }}"></i></a>
        {% endif %}
        <h6>{{ article.date | datetime }}</h6>
    </div>
    <div class="well">
        {{ article.content | safe }}
    </div>
    <div class="well">
        <a href="https://api.pinboard.in/v1/posts/add?url={{ article.link  }}&description={{ article.title }}" rel="noreferrer" target="_blank">
            <img src="{{ url_for('static', filename='img/pinboard.png') }}" title="{{ _('Share on') }} Pinboard" />
        </a>
        <a href="https://reddit.com/submit?url={{ article.link }}&title={{ article.title }}" rel="noreferrer" target="_blank">
            <img src="{{ url_for('static', filename='img/reddit.png') }}" title="{{ _('Share on') }} reddit" />
        </a>
        <a href="https://twitter.com/intent/tweet?url={{ article.link }}&text={{ article.title }}"  rel="noreferrer" target="_blank">
            <img src="{{ url_for('static', filename='img/twitter.png') }}" title="{{ _('Share on') }} twitter" >
        </a>
    </div>
</div><!-- /.container -->
{% endblock %}

src/web/templates/article_pub.html
{% extends "layout.html" %}
{% block content %}
<div class="container" data-article="{{ article.id }}">
    <div class="well">
        <h2><a href="{{ article.link  }}" target="_blank">{{ article.title|safe }}</a></h2>
        <h3>{{ _('from') }} <a href="{{ url_for('feed.feed_pub', feed_id=article.source.id) }}">{{ article.source.title }}</a></h3>
        <h6>{{ article.date | datetime }}</h6>
    </div>
    <div class="well">
        {{ article.content | safe }}
    </div>
    <div class="well">
        <a href="https://api.pinboard.in/v1/posts/add?url={{ article.link  }}&description={{ article.title }}" rel="noreferrer" target="_blank">
            <img src="{{ url_for('static', filename='img/pinboard.png') }}" title="{{ _('Share on') }} Pinboard" />
        </a>
        <a href="https://reddit.com/submit?url={{ article.link }}&title={{ article.title }}" rel="noreferrer" target="_blank">
            <img src="{{ url_for('static', filename='img/reddit.png') }}" title="{{ _('Share on') }} reddit" />
        </a>
        <a href="https://twitter.com/intent/tweet?url={{ article.link }}&text={{ article.title }}"  rel="noreferrer" target="_blank">
            <img src="{{ url_for('static', filename='img/twitter.png') }}" title="{{ _('Share on') }} twitter" >
        </a>
    </div>
</div><!-- /.container -->
{% endblock %}

src/web/templates/bookmarks.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            {{ pagination.info }}
        </div>
        <div class="col-md-6 text-right">
            {% if current_user.is_authenticated %}
                <a class="text-muted" href="{{ url_for('bookmarks.list_') }}">all</a>&nbsp;⸱&nbsp;
                <a class="text-muted" href="{{ url_for('bookmarks.list_') + 'private' }}">private</a>&nbsp;⸱&nbsp;
                <a class="text-muted" href="{{ url_for('bookmarks.list_') + 'public' }}">public</a>&nbsp;⸱&nbsp;
                <a class="text-muted" href="{{ url_for('bookmarks.list_') + 'unread' }}">unread</a>
            {% endif %}
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-6">
            {% if tag %}
                <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>&nbsp;&nbsp;{{ tag }}
            {% endif %}
            {% if query %}
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;&nbsp;{{ query }}
            {% endif %}
        </div>
        <div class="col-md-6 text-right">
            <form method="GET">
                <div class="form-inline">
                    <input type="text" name="query" class="form-control" />
                    <button type="submit" class="btn btn-default">Search</button>
                </div>
            </form>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-8">
            {{ pagination.links }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <ul class="list-group">
            {% for bookmark in bookmarks %}
                <li class="list-group-item">
                    <a href="#">
                        <h4 class="list-group-item-heading">
                            <a href="{{ bookmark.href }}">{{ bookmark.title }}</a>
                        </h4>
                        <p class="list-group-item-text">
                            <div class="text-muted">{{ bookmark.description }}</div>
                            <div>{% for tag in bookmark.tags %}<a href="{{ url_for('bookmarks.list_', tag=tag.text) }}">{{ tag.text }}&nbsp;</a>{% endfor %}</div>
                            {{ bookmark.time | datetime }}
                            {% if current_user.is_authenticated %}
                                <a class="text-muted" href="{{ url_for('bookmark.form', bookmark_id=bookmark.id) }}">edit</a>
                                <a class="text-muted" href="{{ url_for('bookmark.delete', bookmark_id=bookmark.id) }}">delete</a>
                            {% endif %}
                        </p>
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-8">
            {{ pagination.links }}
        </div>
    </div>
</div><!-- /.container -->
{% endblock %}

src/web/templates/edit_bookmark.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="well">
        <h3>{{ action }}</h3>
        <form action="" method="post" name="save" class="form-horizontal">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label for="{{ form.href.id }}" class="col-sm-3 control-label">{{ form.href.label }}</label>
                <div class="col-sm-9">
                    {{ form.href(class_="form-control", size="100%") }}
                </div>
                {% for error in form.href.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}
            </div>

            <div class="form-group">
                <label for="{{ form.title.id }}" class="col-sm-3 control-label">{{ form.title.label }}</label>
                <div class="col-sm-9">
                    {{ form.title(class_="form-control", size="100%") }}
                </div>
                {% for error in form.title.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}
            </div>

            <div class="form-group">
                <label for="{{ form.description.id }}" class="col-sm-3 control-label">{{ form.description.label }}</label>
                <div class="col-sm-9">
                    {{ form.description(class_="form-control", size="100%") }}
                </div>
                {% for error in form.description.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}
            </div>

            <div class="form-group">
                <label for="{{ form.tags.id }}" class="col-sm-3 control-label">{{ form.tags.label }}</label>
                <div class="col-sm-9">
                    {{ form.tags(class_="form-control", size="100%") }}
                </div>
                {% for error in form.tags.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}
            </div>

            <div class="form-group">
                <label for="{{ form.shared.id }}" class="col-sm-3 control-label">{{ form.shared.label }}</label>
                <div class="col-sm-9">
                    <div class="checkbox">
                        {{ form.shared(class_="checkbox",  style="margin-left: 0px;") }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="{{ form.to_read.id }}" class="col-sm-3 control-label">{{ form.to_read.label }}</label>
                <div class="col-sm-9">
                    <div class="checkbox">
                        {{ form.to_read(class_="checkbox",  style="margin-left: 0px;") }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    {{ form.submit(class_="btn btn-default") }}
                </div>
            </div>
        </form>
    </div>
    {% if action == _('Add a new bookmark') %}
        <div class="row">
            <div class="col-md-6 pull-right">
                <p>{{ _('You can add a bookmark with a bookmarklet. Drag the following button to your browser bookmarks.') }}</p>
                {{ _('<a class="btn btn-default" href="%(bookmarklet)s" rel="bookmark">Bookmark this page using Newspipe</a>', bookmarklet='javascript:window.location="%s?href="+encodeURIComponent(document.location)+"&title="+document.title' % url_for('bookmark.bookmarklet', _external=True)) }}
            </div>
            <div class="col-md-6">
                <form action="{{ url_for('bookmark.import_pinboard') }}" method="post" id="formImportPinboard" enctype="multipart/form-data">
                    <p>{{ _('Import bookmarks from Pinboard') }} (*.json)</p>
                    <span>
                        <input type="file" name="jsonfile" />
                        <br />
                        <button class="btn btn-default btn-default" type="submit">OK</button>
                    </span>
                </form>
            </div>
        </div>
    {% endif %}
</div><!-- /.container -->
{% endblock %}

src/web/templates/feeds.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>{{ _('You are subscribed to %(feed_count)d feeds.', feed_count=feeds.count()) }} <a href="{{ url_for("feed.form") }}">{{ _('Add') }}</a> {{ _('a feed') }}.</h1>
    {% include "feed_list.html" %}
</div><!-- /.container -->
{% endblock %}

src/web/templates/history.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>{{ _('History') }}</h1>
    {% if month != None %}
        <h2><a href="{{ url_for("articles.history", year=year) }}"><span class="glyphicon glyphicon-chevron-left"></span> {{ year }}</a></h2>
        <h3>{{ month | month_name }}</h3>
    {% elif year != None %}
        <h2><a href="{{ url_for("articles.history") }}"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp{{ _('all years') }}</a></h2>
        <h3>{{ year }}</h3>
    {% endif %}
    <ul class="list-group">
    {% for article in articles_counter | sort(reverse = True) %}
        {% if year == None %}
            <li class="list-group-item"><a href="{{ url_for("articles.history", year=article) }}">{{ article }}</a> : {{ articles_counter[article] }} articles</li>
        {% elif month == None %}
            <li class="list-group-item"><a href="{{ url_for("articles.history", year=year, month=article) }}">{{ article | month_name  }}</a> : {{ articles_counter[article] }} articles</li>
        {% else %}
            {% for article in articles %}
                <li class="list-group-item">{{ article.date | datetime }} - <a href="/article/{{ article.id }}">{{ article.title | safe }}</a></li>
            {% endfor %}
        {% endif %}
     {% endfor %}
     </ul>
</div><!-- /.container -->
{% endblock %}